/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardIdRouteImport } from './routes/card.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/council': typeof CouncilRoute
  '/settings': typeof SettingsRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/council': typeof CouncilRoute
  '/settings': typeof SettingsRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/council': typeof CouncilRoute
  '/settings': typeof SettingsRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/council' | '/settings' | '/card/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/council' | '/settings' | '/card/$id'
  id: '__root__' | '/' | '/council' | '/settings' | '/card/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouncilRoute: typeof CouncilRoute
  SettingsRoute: typeof SettingsRoute
  CardIdRoute: typeof CardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouncilRoute: CouncilRoute,
  SettingsRoute: SettingsRoute,
  CardIdRoute: CardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
